language: csharp

sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - libunwind8

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
    - os: osx
      mono: latest

env:
  global:
  - CLI_VERSION=1.0.0-rc4-004771
  - COMMIT=${TRAVIS_COMMIT::8}
  - AWS_ACCESS_KEY_ID=MOCK_ID
  - AWS_SECRET_ACCESS_KEY=MOCK_SECRET_KEY
  - AWS_SESSION_TOKEN=MOCK_SESSION_TOKEN
  - secure: "H5wkF2579efgwqXuduwoxyEVQP+GzKtTGA7sjgMkhkHdpKjnjB0g4MKjVjAaMuG1l4GOwqdVztv6U17yE49oWlO2MkAFe3ElMZsTt1DRb0djx5NEqmtyHFxiBCZ2aKD0Hl5jnQubqgknKS5sOwOQtktT5amIl6+LdgXWEfDXEJ0RdSOr3/DzaXbn/cMsZa9IVZFa0lSU+GMmC4Y7RmjGDlj/0i3GdrKJ6poOXX5H37x0isfTndCmzX7guKdFpZCK4aMrc99XoSxqLPrGMumpjm1lP1N79F8N4h3iYjEa/GAPTIqVcJOv5uRmAcmLrjm1Jb2QrrpUh7sUWovgMJ0il/LVMWu+5rvy4QZ+GMSSkOWBNue0JoCNTUUauXoS5YWUAU9pWnZJOp6n2p53o6rb0j530HhBmQdGIE7rWVwO23tajbNiPNEiFEe6M9ZQ5hhWxE8pCqSzcS8x7uWxAp6Q42JwO2tYi9GYpVr+G8rKYyoyBpqlDql7EdAqetz/X4Y1jHW4ATIpZE9ldFHzEwt29aAeXB91yA8dIoPdfGr8idzQn5i/9XQ9esKM9siTQtdqP23RYo2uA3CFmOEyJc32kEsgg+dtJ2SITiU6z1W+kZoQ5M+HE5ialtP0wp1ooSlZPV3iv1zXaiGclpwAdXUXo8uHNOz4oJvPth/Y6z0RJCM="

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; brew link --force openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed --with-default-names; fi

install:
  - npm install semver -g
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull dwmkerr/dynamodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -d -p 8000:8000 dwmkerr/dynamodb -sharedDb -inMemory; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir /tmp/dynamodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O - https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xzC /tmp/dynamodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -Xss1m -Xms320m -Xmx320m -jar /tmp/dynamodb/DynamoDBLocal.jar -port 8000 -inMemory & fi
  - chmod u+x build.sh
  - chmod u+x ./scripts/set-build-version.sh
  - chmod u+x ./scripts/patch-version.sh
  - chmod u+x ./scripts/push-to-nuget.sh
  - eval $(./scripts/set-build-version.sh)
  - ./scripts/patch-version.sh --version=$PROJECT_BUILD_VERSION
  - export PATH=$PATH:$HOME/.local/bin
  - dotnet --info

script:
  - ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=Release --pack

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [ ! -z "$TRAVIS_TAG" ] && semver $TRAVIS_TAG &>/dev/null; then ./scripts/push-to-nuget.sh --apikey=$NUGET_API_KEY --version=$PROJECT_BUILD_VERSION; fi